### ISSUE TITLE
Go back to 100% coverage

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#105]

**Comment by rho62** [comment]
Hei Waldir,

As usual I’m falling behind – But I’ve certainly not abandoned the project, though I know that my credibility is low. But always other stuff that comes across. Can we have a meeting on these recent issues? I’m available tomorrow.

/René
Fra: Waldir Leoncio ***@***.***>
Svar til: ocbe-uio/TruncExpFam ***@***.***>
Dato: mandag 26. februar 2024 kl. 16:44
Til: ocbe-uio/TruncExpFam ***@***.***>
Kopi: Subscribed ***@***.***>
Emne: [ocbe-uio/TruncExpFam] Go back to 100% coverage (Issue #105)

**Comment by wleoncio** [comment]
Hi René,

Thanks for the reminder! I've just released version 1.1.1 with a hotfix to a critical issue (#103); I was going to write you as soon as the CRAN checks for the latest version are done, but in general everything is under control.

Here's a breakdown of the currently opened issues, from oldest to newest:

- #54: making steady progress. 3/12 `ptrunc()` methods are implemented, work on `qtrunc()` will follow.
- #102 could wait until the issue on the point above is completed
- #103 is critical but seems fixed. I am keeping an eye on the [CRAN checks](https://cran.r-project.org/web/checks/check_results_TruncExpFam.html) page until all "version" columns say 1.1.1 and all statuses are "OK"
- #104 would just have me try removing an ellipsis argument I don't think we need (but S3 rules might force me to)
- #105 is just housekeeping. Some of our recent code is not covered by unit tests, but this is easy to fix and won't affect behavior.

Today's a bit cramped for me, but I can meet at 15:00. Let me know if you wanna meet to go over those in more detail. :)

**Comment by rho62** [comment]
Hi Waldir,

Thanks for the update. A meeting at 15:00 would be fine.

/René



Fra: Waldir Leoncio ***@***.***>
Svar til: ocbe-uio/TruncExpFam ***@***.***>
Dato: fredag 1. mars 2024 kl. 06:22
Til: ocbe-uio/TruncExpFam ***@***.***>
Kopi: Rene Holst ***@***.***>, Comment ***@***.***>
Emne: Re: [ocbe-uio/TruncExpFam] Go back to 100% coverage (Issue #105)


Hi René,

Thanks for the reminder! I've just released version 1.1.1 with a hotfix to a critical issue (#103<https://github.com/ocbe-uio/TruncExpFam/issues/103>); I was going to write you as soon as the CRAN checks for the latest version are done, but in general everything is under control.

Here's a breakdown of the currently opened issues, from oldest to newest:

  *   #54<https://github.com/ocbe-uio/TruncExpFam/issues/54>: making steady progress. 3/12 ptrunc() methods are implemented, work on qtrunc() will follow.
  *   #102<https://github.com/ocbe-uio/TruncExpFam/issues/102> could wait until the issue on the point above is completed
  *   #103<https://github.com/ocbe-uio/TruncExpFam/issues/103> is critical but seems fixed. I am keeping an eye on the CRAN checks<https://cran.r-project.org/web/checks/check_results_TruncExpFam.html> page until all "version" columns say 1.1.1 and all statuses are "OK"
  *   #104<https://github.com/ocbe-uio/TruncExpFam/issues/104> would just have me try removing an ellipsis argument I don't think we need (but S3 rules might force me to)
  *   #105<https://github.com/ocbe-uio/TruncExpFam/issues/105> is just housekeeping. Some of our recent code is not covered by unit tests, but this is easy to fix and won't affect behavior.

Today's a bit cramped for me, but I can meet at 15:00. Let me know if you wanna meet to go over those in more detail. :)

**Comment by wleoncio** [comment]
Need to get #107 fixed before finishing this, as the remaining uncovered code block is related to calling `rtruncnbinom()` providing `mu` instead of `prob`.
