### ISSUE TITLE
Join truncation limits into one slot

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#16]
Truncation limits are currently defined as separate slots in the `Trunc` class:

https://github.com/ocbe-uio/TruncExpFam/blob/32e40d315536f404c2d40552bb10d2cb020495b1/R/classes.R#L11-L19

They should be joined as a 1+ vector into one slot, as it may have length 1, 2, 3.

**Comment by rho62** [comment]
I’m not sure if I got this wrong, but just to be sure: There are always two truncation limits: a left and a right. And in case one or both of them are missing, there are default values corresponding to the lower and uppe limits of the domain for that particular distribution

/R

21. jan. 2021 kl. 11:26 skrev Waldir Leoncio <notifications@github.com<mailto:notifications@github.com>>:



Truncation limits are currently defined as separate slots in the Trunc class:

https://github.com/ocbe-uio/TruncExpFam/blob/32e40d315536f404c2d40552bb10d2cb020495b1/R/classes.R#L11-L19

They should be joined as a 1+ vector into one slot, as it may have length 1, 2, 3.

**Comment by wleoncio** [comment]
> there are default values corresponding to the lower and uppe limits of the domain for that particular distribution

OK, the default limits will be handled on issue #14 and implemented on each rtrunc method.

As for the quantity: if there are always going to be two truncation limits, maybe it's OK to leave two slots for them. We can come back to this a bit later to decide between that and having one slot that accepts a vector, as currently I can only see slight advantages and disadvantages to each approach.

**Comment by wleoncio** [comment]
@rho62, the "slot" discussion I mentioned above doesn't apply anymore since we've decided to use S3. However, we should still decide whether to keep the truncation limits separate when calling `rtrunc()` or if they should be passed together, as a length-2 vector. In other words, do you prefer this:

```
rtrunc(n=100, mean=5, sd=2, family="gaussian", a=2, b=3)
```

or this:


```
rtrunc(n=100, mean=5, sd=2, family="gaussian", ab=c(2, 3))
```

Of course, `ab` could have another name, something potentially more informative such as `trunc.limits`.

**Comment by wleoncio** [comment]
Decided on first behavior, which allows for the specification of only one of the limits.
