### ISSUE TITLE
Arguments for rtrunc.norm don't match those on stats::rnorm 

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#22]
The `stats::rnorm` function uses `mean` and `sd`, whereas `rtrunc.norm` uses `mu` and `sigma`. @rho62, should we change the latter to match the former?

**Comment by rho62** [comment]
Yes, Thx for observing

22. jan. 2021 kl. 10:00 skrev Waldir Leoncio <notifications@github.com<mailto:notifications@github.com>>:



The stats::rnorm function uses mean and sd, whereas rtrunc.norm uses mu and sigma. @rho62<https://github.com/rho62>, should we change the latter to match the former?

**Comment by wleoncio** [comment]
Alright! Ditto for the Gamma (`alpha -> shape` and `beta -> rate`)? We can implement a `scale` argument later.

P.S.: Also, for the lognormal.

**Comment by rho62** [comment]
yep, and I believe scale=1/rate

PS: I read all of these mails comming from you via ocbe-uio/TruncExpFam, but I’m a little uncertain which you want me to reply to. Most of them looks more like GH generated comments for yourself in response to action you do. Let me know if you want something from me

22. jan. 2021 kl. 10:15 skrev Waldir Leoncio <notifications@github.com<mailto:notifications@github.com>>:



Alright! Ditto for the Gamma (alpha -> shape and beta -> rate)? We can implement a scale argument later.

**Comment by rho62** [comment]
Yes, it should conform with rnorm. Thanks for observing this
