### ISSUE TITLE
Include more distributions

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#24]
Add methods for these distributions:

- [x] Negative binomial
- [x] Exponential
- [ ] Laplace
- [x] Inverse gaussian
- [ ] Generalized inv gaussian
- [x] Beta

This depends on several generic functions being in place. In other words, the following issues must be closed first to avoid rework:

- [x] #5 
- [x] #9 
- [x] #10
- [x] #21

**Comment by rho62** [comment]
The necessities for the following distr have been calculated

- Inverse Gamma
- Inverse Gaussian
- Beta
- Chi Square
- Exponential 
- Bernoulli

The Laplace and Generalized Inv Gaussian are not imperative now

**Comment by wleoncio** [comment]
As per issue #30, the distributions checked above have been coded. Their complete support in the package, starting with `rtrunc()`, is being tracked by that issue, so this one seems to be satisfactory completed and will be thus closed.
