### ISSUE TITLE
Check that all parameters from stats::r* appear in the respective rtrunc methods

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#29]
~mu -> mean~ (tracked by issue #22)
~mulog -> meanlog~ (tracked by issue #22)
~sigma -> sd~ (tracked by issue #22)
~sigmalog -> sdlog~ (tracked by issue #22)

Also check that all parameters are included in all functions in rtrunc.R

**Comment by wleoncio** [comment]
Argument renaming is tracked by issue #22. I think it's worth keeping this one open for the second part, though.

**Comment by wleoncio** [comment]
Affected functions that need proper handling of parameter passing so it matches stat:

- [x] Gamma (can be passed as shape and rate or shape and scale);
- [x] Inverted gamma (same thing)

Once these are handled, we can close the issue (and reopen if something else is detected).
