### ISSUE TITLE
Classes.R file

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#32]
Go through the file: 

- Update parameter lists
- Add new classes for the new distributions

**Comment by wleoncio** [comment]
Agreed. This is critical, otherwise the new distros won't work because the classes it uses are not defined.

**Comment by wleoncio** [comment]
As a consequence of solving issue #36, current package version (0.0.9003) dropped S4 in favor of S3, so formal class definitions are no longer necessary.
