### ISSUE TITLE
Find suitable limits for non-symmetrical distributions

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#33]
Find suitable limits for non-symmetrical distributions (eg. Gamma, Inv Gaussian, LogNormal etc)

**Comment by wleoncio** [comment]
For now, use the same as the ones on stats (e.g. `rate=1` for `rgamma`).

Implement for all non-symmetric distros in the code (i.e. everything except Normal).

**Comment by wleoncio** [comment]
Wait for #30 so invisible functions are also included.

**Comment by wleoncio** [comment]
Resolved with #73, especially commit 0c81c42c4b4196d75d6bbafd3397a61c5eeb87ed.
