### ISSUE TITLE
Create package logo

### ISSUE THREAD

**Issue by wleoncio** [ocbe-uio/TruncExpFam#45]
Try to use `hexSticker::sticker()`.

**Comment by rho62** [comment]
Hi Waldir

I’ve worked on issue #30 and some other stuff. However I run into some github problems when I try to push the changes :

remote: error: GH006: Protected branch update failed for refs/heads/develop.
remote: error: At least 1 approving review is required by reviewers with write access.

Little nervous to do some alternatives, as I uncertain about the implications. Should I create a new branch and push it to that?

/René
