### ISSUE TITLE
Sampling n units

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#46]
The sampling functions rXXX do most often not sample the full sample n, due to truncation

**Comment by wleoncio** [comment]
Got it. So the value of `n` passed by the user should be the one they get in the end, if I understood correctly. The first solution that coems to mind would be to wrap the call to `stats::r` in some kind of loop (`while` comes to mind, though working with those requires very careful planning to avoid an infinite loop). I'll give this a bit more thought.
