### ISSUE TITLE
Remove redundant code

### ISSUE THREAD

**Issue by rho62** [ocbe-uio/TruncExpFam#48]
In rtrunc.normal:
        .....
	if (!missing(b)) {
		y <- y[y <= b]
	} else {
		b <- Inf
	}
	class(y) <- "trunc_normal"
	return(y)

Guess "else {b<-Inf } can" be deleted? 

The same issue applies for other distributions gamma ao

**Comment by wleoncio** [comment]
OK

**Comment by wleoncio** [comment]
Mostly, this is about if-statements containing `else b <- inf`. There's another one on `gamma.R` (as OP mentioned), and a quick search would find the rest.
